replicaCount: 1

image:
  repository: hub.storeinvoice.app/mithrilforge
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 3000

ingress:
  enabled: true
  hosts:
    - host: mithrilforge.ksnll.com
      paths:
        - path: /
          pathType: Prefix
